### ISSUE TITLE
Which version of nodejs has `--no-global-gc-scheduling` flag enabled?

### ISSUE THREAD

**Issue by izyak** [TusimaNetwork/zkBridge-lightClient#1]
To run run.sh file within verify_header,
```sh
SLOT=6154570 bash run.sh
```
It needs a version of patched node, which has `--no-global-gc-scheduling` flag, which is not available in the current versions.
```sh
# A patched node
NODE_PATH=../../../node/out/Release/node
```

Where do I get this version of node?

**Comment by iwanwang-0** [comment]
Sorry for the confusion due to the lack of documentation. Please check [here](https://github.com/TusimaNetwork/zkBridge-lightClient/blob/main/circuits/docs/installation-for-patched-node.md).
